# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fengqiao_pb2 as fengqiao__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fengqiao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SemanticServiceStub:
    """=== Semantic Analysis Service ===
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeSimilarity = channel.unary_unary(
                '/fengqiao.SemanticService/ComputeSimilarity',
                request_serializer=fengqiao__pb2.SimilarityRequest.SerializeToString,
                response_deserializer=fengqiao__pb2.SimilarityResponse.FromString,
                _registered_method=True)
        self.BatchDedup = channel.unary_stream(
                '/fengqiao.SemanticService/BatchDedup',
                request_serializer=fengqiao__pb2.DedupRequest.SerializeToString,
                response_deserializer=fengqiao__pb2.DedupProgress.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/fengqiao.SemanticService/GenerateReport',
                request_serializer=fengqiao__pb2.ReportRequest.SerializeToString,
                response_deserializer=fengqiao__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/fengqiao.SemanticService/HealthCheck',
                request_serializer=fengqiao__pb2.HealthRequest.SerializeToString,
                response_deserializer=fengqiao__pb2.HealthResponse.FromString,
                _registered_method=True)


class SemanticServiceServicer:
    """=== Semantic Analysis Service ===
    """

    def ComputeSimilarity(self, request, context):
        """语义相似度计算
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchDedup(self, request, context):
        """批量去重（流式返回进度）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """AI 分析报告生成
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeSimilarity': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeSimilarity,
                    request_deserializer=fengqiao__pb2.SimilarityRequest.FromString,
                    response_serializer=fengqiao__pb2.SimilarityResponse.SerializeToString,
            ),
            'BatchDedup': grpc.unary_stream_rpc_method_handler(
                    servicer.BatchDedup,
                    request_deserializer=fengqiao__pb2.DedupRequest.FromString,
                    response_serializer=fengqiao__pb2.DedupProgress.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=fengqiao__pb2.ReportRequest.FromString,
                    response_serializer=fengqiao__pb2.ReportResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=fengqiao__pb2.HealthRequest.FromString,
                    response_serializer=fengqiao__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fengqiao.SemanticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fengqiao.SemanticService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticService:
    """=== Semantic Analysis Service ===
    """

    @staticmethod
    def ComputeSimilarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fengqiao.SemanticService/ComputeSimilarity',
            fengqiao__pb2.SimilarityRequest.SerializeToString,
            fengqiao__pb2.SimilarityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchDedup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fengqiao.SemanticService/BatchDedup',
            fengqiao__pb2.DedupRequest.SerializeToString,
            fengqiao__pb2.DedupProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fengqiao.SemanticService/GenerateReport',
            fengqiao__pb2.ReportRequest.SerializeToString,
            fengqiao__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fengqiao.SemanticService/HealthCheck',
            fengqiao__pb2.HealthRequest.SerializeToString,
            fengqiao__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
